// <auto-generated />
using System;
using ITI_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITI_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912232108_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITI_Project.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Egyptian writer, 1988 Nobel laureate in Literature, best known for the Cairo Trilogy.",
                            Name = "Naguib Mahfouz",
                            Photo = "/images/author/naguib_mahfouz.png"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Colombian novelist and journalist, pioneer of magical realism.",
                            Name = "Gabriel García Márquez",
                            Photo = "/images/author/gabriel_marquez.png"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Spanish novelist known for The Cemetery of Forgotten Books series.",
                            Name = "Carlos Ruiz Zafón",
                            Photo = "/images/author/carlos_zafon.png"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Algerian novelist and poet, one of the best-selling Arabic-language authors.",
                            Name = "Ahlam Mosteghanemi",
                            Photo = "/images/author/ahlam_mosteghanemi.png"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Egyptian journalist and novelist known for socially themed romance fiction.",
                            Name = "Ihsan Abdel Quddous",
                            Photo = "/images/author/ihsan_abdelquddous.png"
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "/images/books/midaq_alley.png",
                            ISBN = "9780978000001",
                            PublishedYear = 1947,
                            Summary = "A portrait of life in a Cairo back alley in the 1940s.",
                            Title = "Midaq Alley"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "/images/books/palace_walk.png",
                            ISBN = "9780978000002",
                            PublishedYear = 1956,
                            Summary = "The first volume of the Cairo Trilogy, following a Cairo family through changing times.",
                            Title = "Palace Walk"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000003",
                            PublishedYear = 1957,
                            Summary = "The second volume of the Cairo Trilogy.",
                            Title = "Palace of Desire"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000004",
                            PublishedYear = 1957,
                            Summary = "The concluding volume of the Cairo Trilogy.",
                            Title = "Sugar Street"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 8,
                            CoverImage = "/images/books/thief_and_dogs.png",
                            ISBN = "9780978000005",
                            PublishedYear = 1961,
                            Summary = "A short, tense novel about a man seeking revenge after prison.",
                            Title = "The Thief and the Dogs"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000006",
                            PublishedYear = 1967,
                            Summary = "Several narrators share their view of the same guesthouse and its residents.",
                            Title = "Miramar"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            BookLanguage = "English",
                            CategoryId = 7,
                            CoverImage = "/images/books/hundred_years_solitude.png",
                            ISBN = "9780978000007",
                            PublishedYear = 1967,
                            Summary = "The multi-generational story of the Buendía family in the town of Macondo.",
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            BookLanguage = "English",
                            CategoryId = 4,
                            CoverImage = "/images/books/love_in_time_of_cholera.png",
                            ISBN = "9780978000008",
                            PublishedYear = 1985,
                            Summary = "A decades-long love story set on the Caribbean coast of Colombia.",
                            Title = "Love in the Time of Cholera"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            BookLanguage = "English",
                            CategoryId = 8,
                            CoverImage = "/images/books/chronicle_of_death_foretold.png",
                            ISBN = "9780978000009",
                            PublishedYear = 1981,
                            Summary = "A reconstruction of a murder that the whole town knew was coming.",
                            Title = "Chronicle of a Death Foretold"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            BookLanguage = "English",
                            CategoryId = 7,
                            CoverImage = "",
                            ISBN = "9780978000010",
                            PublishedYear = 1975,
                            Summary = "A portrait of an aging, unnamed Caribbean dictator.",
                            Title = "The Autumn of the Patriarch"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            BookLanguage = "English",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000011",
                            PublishedYear = 1961,
                            Summary = "A retired colonel waits, year after year, for a pension that never arrives.",
                            Title = "No One Writes to the Colonel"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            BookLanguage = "English",
                            CategoryId = 8,
                            CoverImage = "/images/books/shadow_of_the_wind.png",
                            ISBN = "9780978000012",
                            PublishedYear = 2001,
                            Summary = "A boy discovers a mysterious book and is drawn into a decades-old secret in Barcelona.",
                            Title = "The Shadow of the Wind"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            BookLanguage = "English",
                            CategoryId = 8,
                            CoverImage = "/images/books/angels_game.png",
                            ISBN = "9780978000013",
                            PublishedYear = 2008,
                            Summary = "A young writer strikes a dangerous deal with a mysterious publisher.",
                            Title = "The Angel's Game"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            BookLanguage = "English",
                            CategoryId = 8,
                            CoverImage = "",
                            ISBN = "9780978000014",
                            PublishedYear = 2011,
                            Summary = "A stranger's visit reopens old wounds tied to the Cemetery of Forgotten Books.",
                            Title = "The Prisoner of Heaven"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            BookLanguage = "English",
                            CategoryId = 8,
                            CoverImage = "",
                            ISBN = "9780978000015",
                            PublishedYear = 2016,
                            Summary = "The concluding novel of the Cemetery of Forgotten Books series.",
                            Title = "The Labyrinth of the Spirits"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 4,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000016",
                            PublishedYear = 1993,
                            Summary = "A painter recalls a lost love against the backdrop of Algeria's history.",
                            Title = "Memory in the Flesh"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "/images/books/chaos_of_the_senses.png",
                            ISBN = "9780978000017",
                            PublishedYear = 1997,
                            Summary = "A writer blurs the line between her fiction and her own life.",
                            Title = "Chaos of the Senses"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000018",
                            PublishedYear = 2003,
                            Summary = "The concluding novel of the Memory in the Flesh trilogy.",
                            Title = "Passer of Beds"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "/images/books/black_suits_you.png",
                            ISBN = "9780978000019",
                            PublishedYear = 2012,
                            Summary = "A singer's fame collides with grief and a complicated love.",
                            Title = "Black Suits You"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "/images/books/i_am_free.png",
                            ISBN = "9780978000020",
                            PublishedYear = 1954,
                            Summary = "A young woman pushes back against family and social expectations.",
                            Title = "I Am Free"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 5,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000021",
                            PublishedYear = 1959,
                            Summary = "A story of love and loyalty tested by circumstance.",
                            Title = "Don't Let the Sun Put It Out"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 5,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000022",
                            PublishedYear = 1955,
                            Summary = "A young woman's private reflections on love and independence.",
                            Title = "A Girl's Diary"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 5,
                            BookLanguage = "Arabic",
                            CategoryId = 4,
                            CoverImage = "",
                            ISBN = "9780978000023",
                            PublishedYear = 1957,
                            Summary = "A family drama about jealousy and control across generations.",
                            Title = "I Do Not Sleep"
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "BC-0001",
                            BookId = 1,
                            Status = "Borrowed"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "BC-0002",
                            BookId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "BC-0003",
                            BookId = 2,
                            Status = "Borrowed"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "BC-0004",
                            BookId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "BC-0005",
                            BookId = 3,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "BC-0006",
                            BookId = 3,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "BC-0007",
                            BookId = 4,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "BC-0008",
                            BookId = 4,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "BC-0009",
                            BookId = 5,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "BC-0010",
                            BookId = 5,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "BC-0011",
                            BookId = 6,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "BC-0012",
                            BookId = 6,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "BC-0013",
                            BookId = 7,
                            Status = "Borrowed"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "BC-0014",
                            BookId = 7,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "BC-0015",
                            BookId = 8,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "BC-0016",
                            BookId = 8,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "BC-0017",
                            BookId = 9,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "BC-0018",
                            BookId = 9,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "BC-0019",
                            BookId = 10,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "BC-0020",
                            BookId = 10,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "BC-0021",
                            BookId = 11,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "BC-0022",
                            BookId = 11,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "BC-0023",
                            BookId = 12,
                            Status = "Borrowed"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "BC-0024",
                            BookId = 12,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "BC-0025",
                            BookId = 13,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "BC-0026",
                            BookId = 13,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "BC-0027",
                            BookId = 14,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "BC-0028",
                            BookId = 14,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "BC-0029",
                            BookId = 15,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "BC-0030",
                            BookId = 15,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "BC-0031",
                            BookId = 16,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "BC-0032",
                            BookId = 16,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "BC-0033",
                            BookId = 17,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "BC-0034",
                            BookId = 17,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "BC-0035",
                            BookId = 18,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "BC-0036",
                            BookId = 18,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "BC-0037",
                            BookId = 19,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "BC-0038",
                            BookId = 19,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "BC-0039",
                            BookId = 20,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "BC-0040",
                            BookId = 20,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "BC-0041",
                            BookId = 21,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "BC-0042",
                            BookId = 21,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "BC-0043",
                            BookId = 22,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "BC-0044",
                            BookId = 22,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "BC-0045",
                            BookId = 23,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "BC-0046",
                            BookId = 23,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Self Development"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Mystery"
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("ITI_Project.Model.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 1,
                            BorrowDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4
                        },
                        new
                        {
                            Id = 2,
                            BookCopyId = 3,
                            BorrowDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5
                        },
                        new
                        {
                            Id = 3,
                            BookCopyId = 13,
                            BorrowDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6
                        },
                        new
                        {
                            Id = 4,
                            BookCopyId = 23,
                            BorrowDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MembershipExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@library.local",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Admin@123",
                            PhoneNumber = "01000000001",
                            Role = 2,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.librarian@library.local",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Librarian@123",
                            PhoneNumber = "01000000002",
                            Role = 1,
                            UserName = "sara.librarian"
                        },
                        new
                        {
                            Id = 3,
                            Email = "omar.librarian@library.local",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Librarian@123",
                            PhoneNumber = "01000000003",
                            Role = 1,
                            UserName = "omar.librarian"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mostafa.adel@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122201",
                            Role = 0,
                            UserName = "mostafa_adel"
                        },
                        new
                        {
                            Id = 5,
                            Email = "farida.hassan@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122202",
                            Role = 0,
                            UserName = "farida.hassan"
                        },
                        new
                        {
                            Id = 6,
                            Email = "ahmed.tarek@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122203",
                            Role = 0,
                            UserName = "ahmed.tarek"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mona.saeed@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122204",
                            Role = 0,
                            UserName = "mona_saeed"
                        },
                        new
                        {
                            Id = 8,
                            Email = "youssef.k@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122205",
                            Role = 0,
                            UserName = "youssef.k"
                        },
                        new
                        {
                            Id = 9,
                            Email = "nourhan.ali@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122206",
                            Role = 0,
                            UserName = "nourhan.ali"
                        },
                        new
                        {
                            Id = 10,
                            Email = "karim.mostafa@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122207",
                            Role = 0,
                            UserName = "karim.mostafa"
                        },
                        new
                        {
                            Id = 11,
                            Email = "salma.ibrahim@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122208",
                            Role = 0,
                            UserName = "salma.ibrahim"
                        },
                        new
                        {
                            Id = 12,
                            Email = "hassan.fouad@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122209",
                            Role = 0,
                            UserName = "hassan.fouad"
                        },
                        new
                        {
                            Id = 13,
                            Email = "dina.mahmoud@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122210",
                            Role = 0,
                            UserName = "dina.mahmoud"
                        },
                        new
                        {
                            Id = 14,
                            Email = "amr.samir@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122211",
                            Role = 0,
                            UserName = "amr.samir"
                        },
                        new
                        {
                            Id = 15,
                            Email = "yasmin.adel@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122212",
                            Role = 0,
                            UserName = "yasmin.adel"
                        },
                        new
                        {
                            Id = 16,
                            Email = "tarek.nabil@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122213",
                            Role = 0,
                            UserName = "tarek.nabil"
                        },
                        new
                        {
                            Id = 17,
                            Email = "rania.mostafa@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122214",
                            Role = 0,
                            UserName = "rania.mostafa"
                        },
                        new
                        {
                            Id = 18,
                            Email = "mohamed.essam@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122215",
                            Role = 0,
                            UserName = "mohamed.essam"
                        },
                        new
                        {
                            Id = 19,
                            Email = "heba.khaled@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122216",
                            Role = 0,
                            UserName = "heba.khaled"
                        },
                        new
                        {
                            Id = 20,
                            Email = "ali.hassan@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122217",
                            Role = 0,
                            UserName = "ali.hassan"
                        },
                        new
                        {
                            Id = 21,
                            Email = "mariam.said@example.com",
                            IsBlocked = true,
                            MembershipExpiryDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122218",
                            Role = 0,
                            UserName = "mariam.said"
                        },
                        new
                        {
                            Id = 22,
                            Email = "khaled.omar@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122219",
                            Role = 0,
                            UserName = "khaled.omar"
                        },
                        new
                        {
                            Id = 23,
                            Email = "nada.fathy@example.com",
                            IsBlocked = false,
                            MembershipExpiryDate = new DateTime(2027, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipStartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "Member@123",
                            PhoneNumber = "01011122220",
                            Role = 0,
                            UserName = "nada.fathy"
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ITI_Project.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "A vivid portrait of Cairo life, still feels alive today.",
                            CreatedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            BookId = 7,
                            Comment = "Magical and unforgettable, unlike anything else I've read.",
                            CreatedDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            BookId = 12,
                            Comment = "Beautifully atmospheric mystery set in Barcelona.",
                            CreatedDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 17,
                            Comment = "Poetic and deeply moving, hard to put down.",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 20,
                            Comment = "A powerful story about independence and self-respect.",
                            CreatedDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("ITI_Project.Model.Book", b =>
                {
                    b.HasOne("ITI_Project.Model.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITI_Project.Model.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITI_Project.Model.BookCopy", b =>
                {
                    b.HasOne("ITI_Project.Model.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ITI_Project.Model.Fine", b =>
                {
                    b.HasOne("ITI_Project.Model.Loan", "Loan")
                        .WithOne("Fines")
                        .HasForeignKey("ITI_Project.Model.Fine", "LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("ITI_Project.Model.Loan", b =>
                {
                    b.HasOne("ITI_Project.Model.BookCopy", "BookCopy")
                        .WithMany("Loans")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITI_Project.Model.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ITI_Project.Model.Reservation", b =>
                {
                    b.HasOne("ITI_Project.Model.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITI_Project.Model.Member", "Member")
                        .WithMany("Reservations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ITI_Project.Model.Review", b =>
                {
                    b.HasOne("ITI_Project.Model.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITI_Project.Model.Member", "Member")
                        .WithMany("Reviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ITI_Project.Model.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ITI_Project.Model.Book", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ITI_Project.Model.BookCopy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("ITI_Project.Model.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ITI_Project.Model.Loan", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("ITI_Project.Model.Member", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
